CREATE TABLE USERS (USER_ID INT NOT NULL GENERATED ALWAYS AS IDENTITY, USER_TYPE VARCHAR(255) NOT NULL, FILLED VARCHAR(8) DEFAULT 'N' NOT NULL, USER_NAME	VARCHAR(255) UNIQUE, PASSWORD VARCHAR(60) NOT NULL,PARENT_USER_ID INT, PRIMARY KEY (USER_ID));

CREATE TABLE ORDERS (ORDER_ID INT NOT NULL GENERATED ALWAYS AS IDENTITY, USER_ID INT NOT NULL, BOOK_ID INT NOT NULL, USER_NAME	VARCHAR(255) NOT NULL, ORDER_START_DATE TIMESTAMP, ORDER_END_DATE TIMESTAMP, PRIMARY KEY (ORDER_ID), CONSTRAINT userid_fk FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID), CONSTRAINT bookid_fk FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(BOOK_ID));

CREATE TABLE BOOKS (BOOK_ID INT NOT NULL GENERATED ALWAYS AS IDENTITY, TOTAL_QTY INT NOT NULL, GENRE VARCHAR(255) NOT NULL, PRICE FLOAT NOT NULL, IMAGES  VARCHAR(255), DESCRIPTION VARCHAR(255), KEYWORDS VARCHAR(255),BOOK_NAME VARCHAR(255) NOT NULL, PRIMARY KEY (BOOK_ID));
	
CREATE TABLE LICENSES (LICENSE_ID INT NOT NULL GENERATED ALWAYS AS IDENTITY, USER_ID INT,MAX_QTY INT NOT NULL, LICENSE_START_DATE TIMESTAMP, LICENSE_END_DATE TIMESTAMP,PRIMARY KEY (LICENSE_ID), CONSTRAINT adminuserid_fk FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID));


-----------------------------------------------------------------
--Sample queries.
INSERT INTO USERS (USER_TYPE, USER_NAME, PASSWORD) 
VALUES ('Admin', 'Shinchan', 'Password');

INSERT INTO BOOKS(TOTAL_QTY, GENRE, PRICE, IMAGES, DESCRIPTION, KEYWORDS, BOOK_NAME) VALUES (10, 'Horror', 500.00, 'Dummy_path', 'This is a horror book','horror,Basic Instinct', 'Horror Book');


INSERT INTO ORDERS(USER_ID, BOOK_ID, USER_NAME, ORDER_START_DATE, ORDER_END_DATE) VALUES (1,1,'Shinchan', '2019-07-21 17:25:00', '2019-08-05 17:25:00');

INSERT INTO LICENSES(USER_ID,MAX_QTY,LICENSE_START_DATE,LICENSE_END_DATE) VALUES (1,5,'2019-07-21 17:25:00','2019-08-05 17:25:00');


ALTER TABLE USERS ALTER "PASSWORD" SET DATA TYPE VARCHAR(255);
ALTER TABLE USERS ALTER "PARENT_USER_ID" SET DEFAULT -1;

